# Generated by Django 5.2.3 on 2025-07-01 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='categorized_analysis',
            field=models.JSONField(default=dict),
        ),
    ]
