# Generated by Django 5.2.3 on 2025-07-01 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_analysisresult_categorized_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='matched_skills',
            field=models.JSONField(default=list),
        ),
    ]
