# Generated by Django 5.2.3 on 2025-07-01 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_analysisresult_matched_skills'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='grading_feedback',
        ),
        migrations.RemoveField(
            model_name='analysisresult',
            name='resume_grade',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='improvement_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
