# Generated by Django 5.2.3 on 2025-07-01 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_analysisresult_grading_feedback_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='analysisresult',
            name='rewritten_resume_text',
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='grading_feedback',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='resume_grade',
            field=models.FloatField(default=0.0),
        ),
    ]
