# Generated by Django 5.2.3 on 2025-07-02 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_analysisresult_rewritten_resume_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='custom_job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='analysisresult',
            name='job_role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.jobrole'),
        ),
    ]
