# Generated by Django 5.2.3 on 2025-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_analysisresult_custom_job_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='full_description',
            field=models.TextField(default='', help_text='Paste the full, detailed job description here. This will be sent to the AI for analysis.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobrole',
            name='required_skills',
            field=models.TextField(help_text='Enter a comma-separated list of the most important skills for this role.'),
        ),
    ]
