# Generated by Django 5.2.3 on 2025-07-02 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_jobrole_full_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrole',
            name='category',
            field=models.CharField(blank=True, help_text='e.g., Back-End Developer, Data Scientist', max_length=100, null=True),
        ),
    ]
