# Generated by Django 5.2.3 on 2025-07-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_jobrole_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningResource',
            fields=[
                ('skill_name', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('definition', models.TextField(help_text='A brief, one-sentence definition of the skill.')),
                ('youtube_link', models.URLField(blank=True, help_text='A link to a helpful YouTube tutorial.', max_length=255, null=True)),
                ('course_link', models.URLField(blank=True, help_text='A link to a high-quality course (e.g., Coursera, Udemy).', max_length=255, null=True)),
                ('resume_bullet_template', models.TextField(help_text='A template sentence for a resume bullet point, using {skill} as a placeholder.')),
            ],
        ),
    ]
