# Generated by Django 5.2.3 on 2025-07-07 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_learningresource'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='experience_level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='analysisresult',
            name='extracted_sections',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
