# Generated by Django 5.2.3 on 2025-07-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_analysisresult_experience_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisresult',
            name='extracted_sections',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
