# Generated by Django 5.2.3 on 2025-07-08 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_analysisresult_extracted_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysisresult',
            name='interview_questions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
